ccflags-y := -DEXTERNAL_HDMI_EP952
obj-$(CONFIG_EXTERNAL_HDMI)  += ep952.o
ep952-objs := hdmi_ep952.o EP952api.o EP952Controller.o EP952_If.o EP952SettingsData.o DDC_If.o Edid.o EP952SettingsData.o HDCP.o

